### ISSUE TITLE
regolith-look thinks it needs gnome-terminal

### ISSUE THREAD

**Issue by pghvlaans** [gardotd426/regolith-de#16]
Terminal emulator: st. gnome-terminal is not installed. When I ran `regolith-look refresh`, the following warning and error were returned:

    [WARN] Detected incompatible GNOME Terminal version  (< 3.8)
    [ERR] The installed GNOME Terminal version '' is not compatible with the required (dconf migrated) version >= 3.8!

The command did execute, however.

**Comment by gardotd426** [comment]
This isn't anything to be worried about, part of what `regolith-look` does when you run it is it changes your gnome-terminal profile to match the theme you've chosen. Regolith's st build is included and is set as the default terminal emulator. 

I might look into the code and see if maybe I can get rid of the error message anyway, but for now it's not an issue.

**Comment by gardotd426** [comment]
Do me a favor? Pull in the updates I just made and rebuild and reinstall w/ `makepkg -sfi`, and try again and let me know if the error message is gone and the command still completes fine. I'm in my single-GPU passthrough VM right now playing Apex Legends so I can't actually test it myself because there's no X server running, but it should definitely work.

**Comment by pghvlaans** [comment]
Sorry, I didn't see your message earlier. I brought in the update and verified that `regolith-look.patch` was present. The command does work (the important part), but the error message is still there.

I also saw: `/usr/bin/create-regolith-term-profile: line 140: gnome-terminal: command not found`. I must have missed it last time.

**Comment by gardotd426** [comment]
That's weird, because I uninstalled gnome-terminal and ran regolith-look and didn't get the error. Did you run `makepkg -sfi`? The `f` is critical because otherwise it will just install the packages that are already built. It won't patch anything. 

I would go ahead and just clone it in a new directory, like `git clone https://github.com/gardotd426/regolith-de regolith-de2` and then go into the `regolith-de2` directory and run `makepkg -si`.

**Comment by pghvlaans** [comment]
That's done the trick. Good luck with the project!
