### ISSUE TITLE
Feedback after testing

### ISSUE THREAD

**Issue by justinmoon** [gardotd426/regolith-de#20]
Tested this out on fresh arch virtualbox vm.

The only real problem I noticed was that the little color boxes next to workspace numbers in the nord theme don't look the same 

![screenshot](https://user-images.githubusercontent.com/4335621/107110918-4a95dc00-6811-11eb-9294-2f67b7e5582c.png)

I'll edit this if I notice anything else

**Comment by justinmoon** [comment]
There's also too many choices in lightdm display manager. Would be nice if "regolith" was the only one ...
 
![many-choices](https://user-images.githubusercontent.com/4335621/107111095-ce03fd00-6812-11eb-9136-65e701974adc.png)

**Comment by gardotd426** [comment]
There's no way to avoid the multiple entries. LightDM (and other DMs) gets those entries from /usr/share/xsessions. The dependencies required to run regolith include those files, they don't come from my packages whatsoever. You should get the same behavior on Ubuntu using the official Regolith PPA. But even if not, there's no way for me to do anything about it. gnome-flashback is a hard dependency, as is i3-gaps. Those packages provide those files, and I can't affect other packages, and even if I could it would break those packages. 

You can delete the entries from /usr/share/xsessions yourself if you don't want them there. That's the only option. 

As far as the workspace glyphs, it's because the glyph font for Nord is set to "Font Awesome," and on Ubuntu FontAwesome is packaged as like, one font (or really two, FontAwesome and fontawesome-webfont). But on Arch, there's fa-regular, fa-brands, and fa-solid. if you change it to Solid, you'll see the same glyphs. I'm not sure what the pango name for the font is, but according to the pango documentation it uses fontconfig, so in other words fc-cache, so it should be "Font Awesome 5 Free Regular." You could try putting that in /etc/regolith/styles/nord/typeface, where you see `#define typeface_bar     pango:Source Code Pro Medium 13, FontAwesome 13`, you'd want to change `FontAwesome 13` to `Font Awesome 5 Free Regular 13` or something. 

If we can't figure out the correct name to use, I'll consider just including the Ubuntu version of font awesome in the PKGBUILD, but that would mean adding the Arch build of font awesome to the conflicts, and I don't want to add conflicts if I don't have to.

**Comment by AviusX** [comment]
I'd just like to say that I've been using it on my host machine with Arch for at least a couple weeks now and it works absolutely perfect. I haven't noticed any problems at all. I did replace the bar with polybar though so if there are any problems with that I wouldn't be able to tell.

Thank you for this project. Regolith is basically the only thing that allows me to use a TWM because I don't have to manually configure keys to change brightness, volume, etc.

**Comment by gardotd426** [comment]
Hey, glad to hear it! Yeah replacing the bar with polybar shouldn't be any
sort of issue, it just gets rid of a bunch of customizations made to the i3
bar, but that's up to you. I use polybar when I use i3 as well.

I'm probably gonna put it on the AUR soon, thanks for the feedback.

**Comment by neevparikh** [comment]
I've also found this to be near flawless. I think releasing it to the AUR would be great! Maybe we could do a faster update cycle too, I think the ubuntu version is on 1.5.3?

**Comment by gardotd426** [comment]
You can't really go by version numbers. I have a script that automatically
pulls in all updates, updates the PKGBUILD, and pushes the changes here.
And I run it every week, I just haven't run it the last two because I had
to RMA my GPU. It'll be back on Monday and I'll update again.

**Comment by neevparikh** [comment]
Ahh gotcha, I think the aur's definitely ready for this.

**Comment by gardotd426** [comment]
Yeah I'm thinking so too. But I've talked a lot with the Regolith creator
and he's been slowly trying to transition the DE to be more distro-agnostc,
and so I was kind of holding off but I think it will take a while and so
I'll probably put it up soon after my replacement GPU arrives and just edit
the PKGBUILD as necessary as he modifies everything.

**Comment by gardotd426** [comment]
Live in the AUR now. `regolith-full` for the meta package if you're using an AUR helper and want to install the full DE. If you're using `git clone` with `makepkg -si` then it's `regolith-de`.

**Comment by neevparikh** [comment]
@gardotd426 if we want to transition to the aur one (for automatic updates) is there a way besides uninstalling and reinstalling?

**Comment by gardotd426** [comment]
If you're using an AUR helper, just install `remontoire-full`. Then whenever you update with your AUR helper (such as `yay -Syu` or `paru -Syu`), it'll update all your regolith packages if any updates are available.
