### ISSUE TITLE
Rofication not installing properly

### ISSUE THREAD

**Issue by naib864** [gardotd426/regolith-de#22]
I did multiple installs on arcolinux recently and rofication always seems to be installed wrong. The executables are copied to /usr/bin/, but  the python lib doesn't seem to be installed so all rofication files give the error "module rofication not found".  

The issue can be fixed by cloning the original regolith-rofication repository and running the setup,py there.

**Comment by gardotd426** [comment]
I let ken know. He doesn't include setup.py (or 80_rofication) in the PPA
packages (which makes me really wonder how on earth rofication is working
for PPA users, if it's working at all). Unfortunately, since I plan to put
this on the AUR in the next week or so, I can't include anything that
requires user intervention. So until Ken fixes his discrepancy between the
repo and the PPA, I'll just have to remove it. I've let him know, though,
so it shouldn't be long. The thing is, even if he does include the setup.py
file, it would still require manual intervention, so unless he changes the
way it's packaged, I can't include rofication. I think he recently changed
it because I know it worked previously.

**Comment by gardotd426** [comment]
Gotcha all taken care of, I had to work out some weirdness where Ubuntu (and therefore Regolith) has debhelper which can handle python package installation automagically so some necessary installation files weren't included in the .deb, but it should all be functioning as expected now, I tested it myself and it's working well.

**Comment by naib864** [comment]
Will test it next time I do a fresh install (Which probably will be soon because of distrohopping :D)

**Comment by gardotd426** [comment]
I mean if you have it on your current machine, you can just do a `git pull` and then `makepkg -sfi`.

**Comment by naib864** [comment]
Did a new arch install today, seems to work :)

**Comment by gardotd426** [comment]
Awesome, I'll go ahead and close, feel free to file any additional issues you come across.
