### ISSUE TITLE
Package new upstream release

### ISSUE THREAD

**Issue by malteo** [gardotd426/regolith-de#23]
Looks like a new version has been [released upstream](https://github.com/regolith-linux/regolith-desktop/releases/tag/1.6), with a [couple new features and themes](https://regolith-linux.org/docs/reference/releases/regolith-1.6.0-release-notes/).

**Comment by CookieSource** [comment]
Is this still maintained ?

**Comment by gardotd426** [comment]
Yeah it is. I had to take a break for a while. I've been maintaining it in the meantime, but only following updates on the current upstream branch I was already on. I'll look into moving to the new release. It usually takes some time because there are usually breakages when a new release comes out, but I should have those sorted in a couple days. I'll close this once I have incorporated the changes.

**Comment by gardotd426** [comment]
I'm checking out the new release now and preparing to move everything over. It just takes a shitload of time because there are like 50 packages involved, so it's a lot of tedious work, and then after that I'll surely have to fix the breakages that happen every time there's a new release upstream, but yeah... Anyway in the meantime I've updated the PKGBUILD but there were only two packages that were updated upstream. But it's up-to-date now.

**Comment by gardotd426** [comment]
@malteo So um, I checked the "changes." None of them are relevant whatsoever to this project, except the two new themes, which I will add, and the new app launcher, which I'll also add. The package versions are all the same, it's using the same repo that I've been using, so all packages are the same version (the `release` repo, which I've been using all along). The only other changes were changes to the iso installation (irrelevant here), and an update to i3-gaps (also irrelevant here).

The link you gave to the changes lists all the package versions, and if you look, you'll see that they are the same package versions that I'm using for the PKGBUILD. So yeah, the release is pretty much irrelevant for our purposes. Which isn't that weird, considering they're on a static release model and we're rolling, the reason I chose the "Release" repository is because it means I'm always up to date with the latest release. So yeah, like I said I'll add the two new themes and the new app launcher, but otherwise there's literally nothing to do, because I'm already using all the 1.6 packages. Closing.

**Comment by gardotd426** [comment]
Just FYI, I've incorporated all relevant changes from 1.6:

 - Added the midnight gtk theme and midnight gtk regolith styles config
 - Added solarized-light regolith-styles
 - Added `i3xrocks-app-launcher`
 
Like I said, the only other changes were an update to the iso and a bumping of the i3-gaps version, we're obviously already on the latest i3-gaps version since we're on Arch. All other packages are already from 1.6.
