### ISSUE TITLE
Rofi config doesn't work

### ISSUE THREAD

**Issue by CookieSource** [gardotd426/regolith-de#27]
It seems Rofi isn't picking up the theme from the look selector but instead keeps it default look.

Might be because https://github.com/regolith-linux/regolith-rofi-config isn't installed correctly.
it also seems vala is a dependency required for the panel to function correctly.

**Comment by malteo** [comment]
It seems the problem still persists in `rofication-gui`, because the rofi popup on the notification icon (or by `$mod + n`) still shows the default look, even with latest `1.6-6` package

**Comment by gardotd426** [comment]
yeah, unfortunately there's no fix for that. Rofication doesn't take any arguments, it has no options. And it's a python program, and I don't know python. If you use `downgrade` to downgrade rofi to 1.6.1, you'll see it work again.

I looked at the source code, and it uses xrescat/queries xresources to get the proper theme, but as you know rofi 1.7.0 no longer uses xresources for configuration. And you can't just put `$(xrescat rofi.theme) in the python source code before building, that doesn't work. I know it's possible to call bash functions from within python source code, but that's way beyond my capabilities, and Ken GIlmer (the Regolith creator) is working on 2.0 and has said that he will be doing no refactoring of anything on any 1.X branch (so he's not fixing the rofi stuff either). He's actually moving away from rofi altogether in 2.0, and it's in a very, very pre-alpha state right now, but I'm starting to familiarize myself with the new program he's using to replace rofi, so I can move the PKGBUILD over as soon as it's stable (we will probably get 2.0 before there's actually a Regolith 2.0 release). 

Ken has added me to the Regolith Linux organization, and is welcoming my input, so this will help out a lot with the AUR package, but unfortunately we're at a funny crossroads with the rofi thing. Rofi moved away from Xresources, and Regolith is moving away from Rofi, but there's no stable build of the 2.0 stuff that can be publicly shipped. 

I will say that if I'm able to figure out ilia and drop it in as a replacement for rofi with minimal work, I'll do it well before the 2.0 release. As in I'm working on it now. 

Also, if anyone knows python and might be able to take a look at the regolith-rofication code to see how we might call the correct theme, that would be cool. 

But just to give an example of why this is frustrating:

In the source code, in `rofication/_gui.py`, there's this bit of code:

```
import re
import struct
import subprocess
from typing import Iterable, List

from gi.repository import GLib

from ._client import RoficationClient
from ._notification import Urgency, Notification

HTML_TAGS_PATTERN = re.compile(r'<[^>]*?>')



ROFI_COMMAND = ('rofi',
                '-dmenu',
                '-p', 'Notifications',
                '-markup',
                '-kb-accept-entry', 'Control+j,Control+m,KP_Enter',
                '-kb-remove-char-forward', 'Control+d',
                '-kb-delete-entry', '',
                '-kb-custom-1', 'Delete',
                '-kb-custom-2', 'Return',
                '-kb-custom-3', 'Alt+r',
                '-kb-custom-4', 'Shift+Delete',
                '-markup-rows',
                '-sep', '\\0',
                '-format', 'i',
                '-eh', '2',
                '-lines', '10')
```

Since it's using regular rofi commands, I thought maybe I could just add in the necessary flag and boom. So I tried

```
ROFI_COMMAND = ('rofi',
                '-dmenu',
                '-theme $(xrescat rofi.theme)',
                '-p', 'Notifications',
                '-markup',
                '-kb-accept-entry', 'Control+j,Control+m,KP_Enter',
                '-kb-remove-char-forward', 'Control+d',
                '-kb-delete-entry', '',
                '-kb-custom-1', 'Delete',
                '-kb-custom-2', 'Return',
                '-kb-custom-3', 'Alt+r',
                '-kb-custom-4', 'Shift+Delete',
                '-markup-rows',
                '-sep', '\\0',
                '-format', 'i',
                '-eh', '2',
                '-lines', '10')
```

That obviously didn't work because of course it wouldn't. But then I even tried forcing a theme:

```
ROFI_COMMAND = ('rofi',
                '-dmenu',
                '-theme /etc/regolith/styles/dracula/rofi.rasi',
                '-p', 'Notifications',
                '-markup',
                '-kb-accept-entry', 'Control+j,Control+m,KP_Enter',
                '-kb-remove-char-forward', 'Control+d',
                '-kb-delete-entry', '',
                '-kb-custom-1', 'Delete',
                '-kb-custom-2', 'Return',
                '-kb-custom-3', 'Alt+r',
                '-kb-custom-4', 'Shift+Delete',
                '-markup-rows',
                '-sep', '\\0',
                '-format', 'i',
                '-eh', '2',
                '-lines', '10')
```

And nope. There are other parts of the code in other source files that set xres values and whatnot, I've tried tinkering with those but to no avail. Again I need someone who knows python. But worst case scenario, if ilia is stable enough I'll move Regolith-Arch over to Ilia instead of Rofi.

**Comment by malteo** [comment]
First of all, thank you for the thorough explanation.

Just for anyone's information, forcing a theme works by splitting argument name and value, like

    '-theme', '/etc/regolith/styles/dracula/rofi.rasi',

**Comment by malteo** [comment]
another possible solution, just by patching `rofication/_gui.py`

```diff
--- a/rofication/_gui.py
+++ b/rofication/_gui.py
@@ -1,6 +1,7 @@
 import re
 import struct
 import subprocess
+from contextlib import suppress
 from typing import Iterable, List

 from gi.repository import GLib
@@ -73,6 +74,14 @@ class RoficationGui():
             low = []
             args = []

+            # read theme from X resources
+            with suppress(FileNotFoundError):
+                theme = subprocess.run(["xrescat", "rofi.theme"], capture_output=True, text=True)
+
+                if (theme.returncode == 0):
+                    args.append('-theme')
+                    args.append(theme.stdout)
+
             # reassigns indices of notifications
             for index, notification in enumerate(self._client.list()):
                 notifications.append(notification)
```

**Comment by gardotd426** [comment]
I've already got it. I've patched regolith-look to create a symlink in the user's ~/.config/regolith directory (where things should be going anyway) with the rofi theme, and I've patched  _gui.py and _metadata.py to call on that. 

And the symlink is dynamically replaced every time `regolith-look set themename` is run. This includes with the GUI (mod+alt+L or whatever). It was only a few lines, and it follows regolith's standards of putting user stuff in ~/.config/regolith, and it doesn't require writing anything to the root directory (I'm not saying your solution did, but I'm just saying I made sure of all this before finishing up the patch).  Also it's relatively easy for the user to change if they really want to without knowing python. I'm building the PKGBUILD now (though I've already tested rofication by itself and know my patches work).  

I also went ahead and moved all the i3xrocks modules to pulling from the GH repo instead of extracting .debs (and I will be moving more packages over to this method as I can), so I have quite a big update coming. I'm building it right now to test, then I'll be merging it into master and pushing it to the AUR. Go ahead and give me about 30 minutes and then try to update and see how it works out for you.

**Comment by gardotd426** [comment]
Update is live. So now I've eliminated about 17 .debs and replaced them with direct GH pulls, I've patched regolith-look and rofication to always use the set regolith-look theme, etc. Go ahead and let me know how it works out for y'all.
