### ISSUE TITLE
Fresh Manjaro Gnome Install - i3xrocks error

### ISSUE THREAD

**Issue by mattdemichele-pearson** [gardotd426/regolith-de#35]
On a brand new fresh install of manjaro-gnome-21.2.2-220123-linux515, I get an error for package_regolith-i3xrocks().

"./autogen.sh: line 2: autoreconf: command not found."

Was wondering if you had any ideas? I did this same process about a month ago and it worked. Maybe an outdated package or something?

![image](https://user-images.githubusercontent.com/73609677/153329822-90ea532d-5e94-49f4-86e6-959b5afe7d1b.png)

**Comment by mattdemichele-pearson** [comment]
Nevermind I am dumb - I didn't have base-devel installed. Thanks for putting this package together 👍

**Comment by gardotd426** [comment]
Yeah, I was trying to figure out how you could possibly have a functioning system and any AUR packages installed at all without `base-devel`, since it's literally [required for the AUR](https://wiki.archlinux.org/title/Arch_User_Repository#Getting_started)

># Getting Started
>Ensure the [base-devel](https://archlinux.org/groups/x86_64/base-devel/) package group is installed in full (`pacman -S --needed base-devel`).

I could theoretically put it in the makedepends, but literally `pacman` is part of `base-devel`, you can't have a functioning system *really*, especially including AUR packages, without `base-devel`, so something has happened and you've accidentally removed `autoconf` or something. So I don't even think I should add it as a dependency, but I might, I don't know. I've never seen an AUR package PKGBUILD list `base-devel` in its depends or makedepends, even if the instructions on that AUR packages homepage explicitly say you need `base-devel`

But anyway yeah,  I'm sorry I have to chalk this up to user error on this one, but I will consider adding `base-devel` as a dependency.

**Comment by mattdemichele-pearson** [comment]
Yeah TBH I had assumed it was included in Manjaro so I didn't think of it at first. The OS install was fully functioning though. 

I installed yay through their community repo (just doing a pacman -S yay), instead of building from source, which must somehow not install base-devel as a dependency. At least that is my guess as to what happened.

Sorry for the waste of time - definitely user error.
