### ISSUE TITLE
Regolith 2.0

### ISSUE THREAD

**Issue by Jarvvski** [gardotd426/regolith-de#43]
Hey there

Seeing as Regolith 2.0 is now in beta, will we see a similar release for this AUR version?

http://regolith-desktop.com/

https://fosstodon.org/@regolith/108242139305687235

**Comment by gardotd426** [comment]
Absolutely not. As this repo states, as I've also said several times in issue threads and on places like reddit, this isn't `regolith-de-git`. Nor is it `regolith-de-beta`.

This is `regolith-de`. Which means it doesn't do betas. No package does, unless it's in the name. 

Look at Mesa, or Lutris, or GNOME, or Plasma, or any other project in the repos or the AUR. See if any of them have ever released an update for a beta. It's never been done. 

This project follows actual releases. It will move to 2.0 when 2.0 is released as stable. I have been in communication with Ken (creator of Regolith) for like 6 months about the 2.0 rollout, and have had access to the alpha and the beta in order to test and see if any issues arise. I'm an official member of the Regolith organization on GitHub because I am the developer of more or less the official port of the DE to Arch. It's not "official" in every sense, but I am basically officially the "get Regolith DE on Arch" person. 

If someone wants to take on the impossible task of creating, maintaining, and supporting a beta or -git version of Regolith DE, they are welcome to do it. But due to the nature of how the development has rapidly changed packages and system configs several times the past few months, it's insane and honestly not feasible for a volunteer, not to mention that again, this is a stable release project. I update packages when Regolith releases them to the stable/release branch.

**Comment by Jarvvski** [comment]
Alright, I'm just reffering to a message you already wrote - https://github.com/gardotd426/regolith-de/issues/27#issuecomment-960362832

>  He's actually moving away from rofi altogether in 2.0, and it's in a very, very pre-alpha state right now, but I'm starting to familiarize myself with the new program he's using to replace rofi, so I can move the PKGBUILD over as soon as it's stable (we will probably get 2.0 before there's actually a Regolith 2.0 release).

Chill dude

**Comment by gardotd426** [comment]
Not really sure what there is to chill about. "Absolutely not" is the answer to the question you asked. 

>Alright, I'm just reffering to a message you already wrote

I believe you might be confused. Either that or I am, because you even put my answer in the quote:

>so I can move the PKGBUILD over *as soon as it's stable*

As in as soon as 2.0 has been released as stable. Beta is by definition not that. 

And 2.0 is definitely not out yet. 
![Screenshot_20220510_231526](https://user-images.githubusercontent.com/54234607/167762109-22e23b12-2aa2-4126-b3f2-c0cf6837ed98.png)

If I'm mistaken about what you're asking, please tell me what it is you're actually asking, and it might change the situation. But as you've already seen yourself from that  comment from #27 I already wrote, I said very clearly that I would be moving Regolith DE over to 2.0 as soon as the packages are released as stable. Not beta. That's not even accounting for the fact that releasing a beta would go against Arch and AUR naming guidelines. This is a stable release package set. When Regolith updates the relevant packages as stable releases, I update them here.
