### ISSUE TITLE
gnome-control-center 43 no longer accepts `--class` command line option (or any other GTK options for that matter)

### ISSUE THREAD

**Issue by yawor** [gardotd426/regolith-de#49]
I've been struggling with Super+C and other shortcuts for opening different settings not working at all for me. I've found out that default configuration opens gnome-control-center with `--class=floating_window` command line option. Unfortunately it seems that this and other GTK options have been removed from gnome-control-center. I don't know exact version when that happened.

```
> gnome-control-center --class=floating_window
Unknown option --class=floating_window
```

**Comment by gardotd426** [comment]
Gotcha, I'll have to talk to Ken and see how they're going to go about it, I believe the latest Regolith is built on Ubuntu 22.04 which uses GNOME 43, so they likely haven't even fixed it yet (maybe he has, but I've had to go to him a few times due to things breaking in current verstions that aren't broken *yet* on Ubuntu).

Unfortunately, that's just part of porting a package that runs on Ubuntu to a platform like Arch. Usually shit gets fixed within a couple days though, it's late for me (east coast of US) so it'll have to be tomorrow but I'll get right on it.

**Comment by gardotd426** [comment]
So, I went ahead and took a minute to look, and they've just eliminated launching gnome-control-center as a floating window. I'll push a SMALL update tomorrow that just patches the config file, because I can't pull in the upstream config until I'm done moving everything over to the new 2.0 way of doing things (you have NO idea how much everything has changed, I'm basically having to start completely from scratch here, just like I did with the first port). 

But yeah, just remove `--class=floating_window` from `/etc/regolith/i3/config` (or `~/.config/regolith/i3/config` if that's what you're using) and it will fix your problem. Like I said, I'll push an AUR update tomorrow that does this automatically, but [that is in fact the upstream solution](https://github.com/regolith-linux/regolith-wm-config/blob/main/usr/share/regolith/i3/config.d/60_gnome_config_keybindings#L12) as well, so I'm gonna call this closed.

**Comment by gardotd426** [comment]
Feel free to comment here if you're still having issues after editing (or after my update tomorrow), and I'll gladly re-open the issue

**Comment by yawor** [comment]
Yeah. I've removed the class from the calls and I've added
```
for_window [class="gnome-control-center"] floating enable
```
to keep the behaviour.

**Comment by gardotd426** [comment]
Yeah, I'll probably put a note in the config saying "if you want the
floating ability for gnome control center, use the manual i3 method" the
same way you did with `for_window`, or something like that.
