### ISSUE TITLE
Questions & Test Report

### ISSUE THREAD

**Issue by ghost** [gardotd426/regolith-de#9]
First off, thank you so much for creating this PKGBUILD. I'm very lacking in Arch experience but would absolutely love to finally run Regolith + Arch as my primary OS, Ubuntu/Debian doesn't do it for me anymore... Anyway here's my testing and a few issues I had.

**#Notes**
Manjaro Architect ISO for fresh arch lite install, selected CLI Interface install. 

**#FOR VMWARE USERS THAT ARE TESTING YOU NEED THE FOLLOWING** 
```
pacman -S open-vm-tools xf86-input-vmmouse xf86-video-vmware gtk2 gtkmm dhcpcd

systemctl enable vmtoolsd && systemctl enable dhcpcd && systemctl start vmtoolsd && systemctl start dhcpcd

echo needs_root_rights=yes >>/etc/X11/Xwrapper.config
```

After install, everything appears to be working pretty smoothly, only 2 things I noticed

1. **Missing** compton compositor?, even though its listed to grab from the package (**regolith-compositor-compton-glx**) build but does not list on the output of installed system packages (regolith-i3, regolith-desktop-config, etc are all in Pacman package output though)

2. Small issue with i3 ? Unsure how to solve, see screenshots

<img width="534" alt="Taskbar Arch" src="https://user-images.githubusercontent.com/57725572/92985909-e4d13e00-f484-11ea-8e48-90f937aca969.png">
<img width="496" alt="Taskbar Regolith" src="https://user-images.githubusercontent.com/57725572/92985912-e7cc2e80-f484-11ea-9f8b-df3fc2d8bb2d.png">

3. Fractional scaling is an option default on Regolith Settings app but missing from the Settings app in Arch

4. Why the mention of the conflict with gnome-shell & gdm on the README? On the newest Rigolith install GDM isn't installed as the default, appears the default is lightdm which is what I installed & works great.

**Comment by gardotd426** [comment]
>Missing compton compositor?, even though its listed to grab from the package (regolith-compositor-compton-glx) build but does not list on the output of installed system packages (regolith-i3, regolith-desktop-config, etc are all in Pacman package output though)

`regolith-compositor-compton-glx` Does get installed. It's part of `regolith-desktop-config`:

![Screenshot_20200911_233241](https://user-images.githubusercontent.com/54234607/92986198-1814cc80-f487-11ea-8712-fd72bbf32691.png)

but that does not provide compton/picom, it only provides the Regolith compton config. Picom isn't a hard dependency of regolith, and therefore it doesn't get installed and is instead listed in the optdepends. If you look at the package information for `regolith-desktop-config`, you'll see picom (compton is dead, it's now picom) in the "Optional Dependencies" section. 

That's how packaging is supposed to work, you're not supposed to include packages as dependencies that aren't actual hard dependencies (i.e., if they aren't required for the package to function), and picom isn't a hard dependency of regolith. The *config* file, however, obviously is, which is why it's included. That way, if the user chooses to install picom, they'll have the default regolith compton config ready to go. 

It's just like how latte isn't a dependency of plasma or how picom/compton isn't a dependency of i3. It's just not a dependency and therefore I can't include it as one, or else there will be an inundation of complaints once I *do* post it in the AUR. Hopefully you understand what I'm saying. I've included it in the optional dependencies, but that's all I can do. 

>Small issue with i3 ? Unsure how to solve

I'm assuming you're referring to the missing character next to the thermometer icon? 

I'm guessing that's a VMWare issue, or something, because on virt-manager with QEMU I don't see that issue, nor do I see it on bare metal. It's supposed to just give a temperature readout, though obviously that won't work without 1) running `sensors-detect` and 2) running on bare-metal. 

As far as having slightly different modules on the bar by default, it seems regolith for some reason has changed their default i3xrocks config on the current release, even though the very config file they provide in the "stable" launchpad repo is the one we use (minus removing one problematic module that Regolith doesn't use anyway).

That said, while I look into some stuff, would you try installing `ttf-material-design-icons-git` from the AUR? I notice that the regolith i3 config tells i3xrocks to use it as one of it's fonts. Do that and then log out and back in (I don't trust restarting i3 in place) and see if it's still there. But FWIW, on virt-manager here's what I see:

![Screenshot_20200911_234407](https://user-images.githubusercontent.com/54234607/92986922-37622880-f48c-11ea-9adf-91e657e3d92a.png)

And other testers' screenshots have never shown this issue, and I haven't changed anything that would cause it, so I'm thinking it's a VMWare thing, but yeah please go ahead and try installing `ttf-material-design-icons-git` from the AUR (and also probably `adobe-source-code-pro-fonts` from the official repos), log out and back in, and see what happens.

**Comment by apfsx** [comment]
> 
> 
> > Missing compton compositor?, even though its listed to grab from the package (regolith-compositor-compton-glx) build but does not list on the output of installed system packages (regolith-i3, regolith-desktop-config, etc are all in Pacman package output though)
> 
> `regolith-compositor-compton-glx` Does get installed. It's part of `regolith-desktop-config`:....

Thanks for giving me that breakdown, you have no clue how much I appreciate it, cleared up a bunch of things for me. So if I'm understanding correctly its normal for those packages not to show in pacman -Qe, because the PKGBUILD is taking all these DEB's and combining them into the arch package "regolith-desktop-config".

Any word about why has fractional scaling option in Ubuntu but not Arch?

**Comment by gardotd426** [comment]
>Any word about why has fractional scaling option in Ubuntu but not Arch?

Were you using Ubuntu in a VM or on bare metal?

**Comment by apfsx** [comment]
> 
> 
> > Any word about why has fractional scaling option in Ubuntu but not Arch?
> 
> Were you using Ubuntu in a VM or on bare metal?

Both Regolith Linux & Arch + this script was in VM yes

**Comment by gardotd426** [comment]
I'll have to install Regolith tomorrow and look into it, but if I had to guess, either it's something easily fixable, or it's something to do with the fact that we aren't running gnome-shell (because for some reason, Arch's gnome-shell package contains files that Ubuntu's doesn't, and it somehow causes Regolith DE to break on Arch, so it's a hard conflict), but at the same time that doesn't make any sense because Ken Gilmer (the Regolith creator) told me thatt they don't actually use gnome-shell for anything, so that makes it sound like it might be something fixable. I'll try to look into it this weekend.


>So if I'm understanding correctly its normal for those packages not to show in pacman -Qe, because the PKGBUILD is taking all these DEB's and combining them into the arch package "regolith-desktop-config".

Also yes, this is accurate ^^^

**Comment by apfsx** [comment]
> I'll have to install Regolith tomorrow and look into it, but if I had to guess, either it's something easily fixable, or it's something to do with the fact that we aren't running gnome-shell (because for some reason, Arch's gnome-shell package contains files that Ubuntu's doesn't, and it somehow causes Regolith DE to break on Arch, so it's a hard conflict), but at the same time that doesn't make any sense because Ken Gilmer (the Regolith creator) told me thatt they don't actually use gnome-shell for anything, so that makes it sound like it might be something fixable. I'll try to look into it this weekend.
> 
> > So if I'm understanding correctly its normal for those packages not to show in pacman -Qe, because the PKGBUILD is taking all these DEB's and combining them into the arch package "regolith-desktop-config".
> 
> Also yes, this is accurate ^^^

Any word on this? For testing the fractional scaling does not show up unless you have a 4k resolution monitor I'm pretty sure.

**Comment by gardotd426** [comment]
Sorry, I've had a bunch of life stuff going on, and some hardware issues.
I'll try to look into it in the next day or two, or this weekend at the
latest.

**Comment by gardotd426** [comment]
Closing as this isn't really relevant anymore
